Support granular selection of tools to build
JoshuaBrookover/bgfx.cmake pull request #60
Opened 2019-09-18 10:25 UTC by Qix-

Ref #35.

This is one step closer to solving the issue; it allows you to disable/enable tools granularly.

By disabling `geometryc` and `texturev` and only building `shaderc` and `texturec`, I can now successfully pull in an external `meshoptimizer`, `stb`, `freetype2` and `harfbuzz` without any issues.

The edit at the bottom of https://github.com/JoshuaBrookover/bgfx.cmake/issues/35#issuecomment-532594750 explains what needs to be done to have `geometryc` and `texturev` play nicely with parent projects, but those aren't covered by this PR.

2019-09-20 16:57 UTC, JonnyPtn commented
Just for clarity this is almost completely unrelated to #35.

I don't see what this fixes or what the point of it is, but It also won't really break anything, so I don't feel strongly either way

2019-09-20 17:53 UTC, JoshuaBrookover commented
I agree, it has nothing to do with the original issue in #35. It does relate to the discussion taking place in there. It's a good change, especially since texturev forces you to pull in example's dependencies.

2019-09-20 17:53 UTC, JoshuaBrookover commented
Sorry, did not mean to close.

2019-09-20 18:00 UTC, JonnyPtn commented
Probably worth adding a warning/error when trying to build texturev without the examples too so it’s clear?

2020-01-11 12:59 UTC, bwrsandman commented on CMakeLists.txt
> +option( BGFX_BUILD_TOOL_GEOMETRYC "Build bgfx tool: geometryc"                    ${BGFX_BUILD_TOOLS} )
I believe the idiomatic thing to do here is using `cmake_dependent_option`:
```cmake
cmake_dependent_option(BGFX_BUILD_TOOL_TEXTUREV "Build bgfx tool: texturev" ON
                       "BGFX_BUILD_TOOLS" OFF)
cmake_dependent_option(BGFX_BUILD_TOOL_TEXTUREC "Build bgfx tool: texturec" ON
                       "BGFX_BUILD_TOOLS" OFF)
cmake_dependent_option(BGFX_BUILD_TOOL_SHADERC "Build bgfx tool: shaderc" ON
                       "BGFX_BUILD_TOOLS" OFF)
cmake_dependent_option(BGFX_BUILD_TOOL_GEOMETRYC "Build bgfx tool: geometryc" ON
                       "BGFX_BUILD_TOOLS" OFF)
```
https://cmake.org/cmake/help/v3.15/module/CMakeDependentOption.html#module:CMakeDependentOption

2020-01-11 15:20 UTC, Qix- commented on CMakeLists.txt
> +option( BGFX_BUILD_TOOL_GEOMETRYC "Build bgfx tool: geometryc"                    ${BGFX_BUILD_TOOLS} )
We'd have to bump the minimum CMake version in order to use that. If @JoshuaBrookover is okay with that, then this is indeed the correct way to do this.

2020-01-11 17:43 UTC, pezcode commented on CMakeLists.txt
> +option( BGFX_BUILD_TOOL_GEOMETRYC "Build bgfx tool: geometryc"                    ${BGFX_BUILD_TOOLS} )
It's supported by CMake 3.0 as well, no reason to bump version

2020-01-11 18:51 UTC, Qix- commented
@pezcode good catch :)

2020-01-11 18:52 UTC, Qix- commented on CMakeLists.txt
> +option( BGFX_BUILD_TOOL_GEOMETRYC "Build bgfx tool: geometryc"                    ${BGFX_BUILD_TOOLS} )
Good catch @pezcode.

2020-02-25 20:26 UTC, JonnyPtn requested changes
You need to remove the submodule update from this PR

2020-02-25 20:26 UTC, JonnyPtn commented on CMakeLists.txt
> +	add_custom_target( tools )
What's the benefit of this custom target?

2020-02-25 20:34 UTC, JonnyPtn commented on CMakeLists.txt
> +	add_custom_target( tools )
Nevermind - was moved from deleted tools.cmake 👍

2020-06-11 10:22 UTC, closed without merging

2020-06-11 13:28 UTC, Qix- commented
@widberg why was this closed?

2020-06-11 13:46 UTC, widberg commented
It is unrelated to the issue you referenced. You seem to be the only person that needs this. You changed the submodule remotes. If you want I’ll leave it open for others to comment, but the problem you are trying to solve does not appear to exist. I have no intention of merging this.

2020-06-11 14:59 UTC, Qix- commented
> but the problem you are trying to solve does not appear to exist

Is nobody else using this in their project? Shaderc recompiles almost every time we do an incremental rebuild. Relinking it takes almost 20 seconds.

There's something very wrong with the cmake config as-is.

2020-06-12 07:11 UTC, bwrsandman commented
It wasn't going to be merged with the changes to .gitmodules pointing to a different branch than upstream. Not to mention suggestions to fix the PR being ignored for months.
Your quick reply suggests that you are active on github.
I don't mind the issue you're trying to fix and if the PR is cleaned, then I'd very much like to see it merged. 

As for your rebuild issue, have you tried setting the target property EXCLUDE_FROM_ALL from your host projet? https://cmake.org/cmake/help/latest/prop_tgt/EXCLUDE_FROM_ALL.html#prop_tgt:EXCLUDE_FROM_ALL

2020-06-12 15:22 UTC, Qix- commented
> It wasn't going to be merged with the changes to .gitmodules

Guys, I have already mentioned I understood this. This isn't what I'm arguing for.

> As for your rebuild issue, have you tried setting the target property EXCLUDE_FROM_ALL from your host projet?

No, `shaderc` is _not_ part of my own project. It's part of _this_ project.

I'm not going to respond to this, this is an innane discussion. I'll fork and maintain my own.